// <auto-generated />
using System;
using GameAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("GameAPI.Models.PlayerScore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShotsFired")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShotsHit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlayerName");

                    b.HasIndex("Score", "CreatedAt");

                    b.ToTable("PlayerScores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 26, 3, 3, 39, 751, DateTimeKind.Utc).AddTicks(9792),
                            Deaths = 5,
                            Kills = 30,
                            PlayerName = "ProGamer",
                            Score = 1500,
                            ShotsFired = 150,
                            ShotsHit = 120
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 27, 3, 3, 39, 751, DateTimeKind.Utc).AddTicks(9798),
                            Deaths = 3,
                            Kills = 25,
                            PlayerName = "Sniper",
                            Score = 1200,
                            ShotsFired = 100,
                            ShotsHit = 95
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 27, 22, 3, 39, 751, DateTimeKind.Utc).AddTicks(9800),
                            Deaths = 10,
                            Kills = 20,
                            PlayerName = "Rusher",
                            Score = 980,
                            ShotsFired = 200,
                            ShotsHit = 80
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
